### ISSUE TITLE
I can’t find the nonce in the encrypted reader

### ISSUE THREAD

**Issue by eacp** [secure-io/sio-go#14]
#### Bug describtion

I created an encrypted reader and used it with io.Copy to encrypt a file (plain.png) into an encrypted one (enc.png). However, when I create a reader from enc.png, I can’t get the nonce to use it in a new stream.DecryptReader
#### Expected behavior

I thought the mince was in the file and I could decrypt the reader just like in the DARE version.
#### Additional context

1. What version of Go are you using (`go version`)?
1.12
2. What operating system and processor architecture are you using (`go env`)?
Testing on both Windows 10 and Ubuntu 18.04, both GOARCH=amd64
3. Anything else that is important?

**Comment by aead** [comment]
@eacp The nonce and associated data are not stored as part of the encrypted data stream. You have the following options to handle the situation:
 - Use a unique (256 bit) key per data stream (file) and set the nonce to a fixed value (e.g. all zeros).
 - Store the nonce (and associated data) together with the encrypted data. Therefore you have several options - e.g. write the nonce to the encrypted file before writing the encrypted content, like:
```
if _, err = file.Write(nonce); err != nil {
     // TODO: error handling
}
if _, err = io.Copy(file, encReader); err != nil {
     // TODO: error handling
}
```   
When decrypting you need to do the reverse and read the nonce from the encrypted file and then wrap it with a `DecReader/Writer`. 

How to handle the associated data and nonce value depends on the application in the general case.
