### ISSUE TITLE
Ability to encrypt/decrypt in other languages (such as Java) 

### ISSUE THREAD

**Issue by Sam-Kramer** [secure-io/sio-go#61]
#### Bug description
Currently, I'm attempting to read data encrypted by sio in go in a Java process, and decryption fails. Furthermore, the reverse (i.e encrypt in Java, decrypt in Go) also fails. Both instances work fine on encrypting/decrypting within their own language, but cross-language, it doesn't appear to work. This signifies to me, that there's a potential deviation with the implementation of the encryption algorithms. Also appears to have issues within Python (https://stackoverflow.com/questions/67637920/aes256-gcm-compatibility-encrypt-in-go-decrypt-in-python). 

#### Expected behavior
Ability to encrypt/decrypt, regardless of language. 

#### Additional context

1. What version of Go are you using (`go version`)?
`go version go1.16.7 darwin/amd64`

2. What operating system and processor architecture are you using (`go env`)?
Mac OSX, AMD64

3. Anything else that is important?

I'm using bouncycastle to support the decryption. You can find the java code here: https://gist.github.com/Sam-Kramer/68b3faba34ac6d5c7aed2b784241abb1

I'm attempting to mirror what MinIO does for encryption/decryption: https://github.com/minio/madmin-go/blob/main/encrypt.go#L38

What I've tested/ensured:
1. The reading of nonce, salt, and the cipher data is done correctly (confirmed by comparing outputs in the debugger)
2. Instead of doing key generation in java, I do the key generation in Go (in the decrypt path), grab it via debugger, and then simply only do the decryption in Java. This also does not work. 
3. I've added padding to the nonce in Java, as I see 8-byte nonce get padded in the go code (https://github.com/secure-io/sio-go/blob/master/sio.go#L285) 

My only potential thought on the issue is that it occurs due to the incrementation of the IV. I see that in Go, each fragment we increment the IV (https://github.com/secure-io/sio-go/blob/master/reader.go#L380), which I doubt we do in Java.

**Comment by Sam-Kramer** [comment]
Also if it's isn't obvious from my writing, I have very little knowledge of crypto, so apologies in advance in something comes across as nonsensical.

**Comment by Sam-Kramer** [comment]
Ah, I see the obvious errors in my ways now.

I see that we encrypt each chunk, with it's unique IV, and with additional data of an empty byte array (which is just an encrypted empty byte array, with the initial IV, seq = 0).

**Comment by aead** [comment]
Hi @Sam-Kramer 
`sio` implements an online authenticated encryption scheme (OAE). An OAE can be used to encrypt (arbitrary) long data streams securely - in contrast to an AEAD (like AES-GCM), which can only encrypt messages that fit into RAM securely.
Particularly decrypting a contentious data stream simply with AES-GCM is not secure.

The following image shows what `sio` does to a data stream:
https://raw.githubusercontent.com/secure-io/sio/master/img/channel_construction.svg

Here `l` is the chunk size - e.g. 16 KB, `AEAD` may be for example AES-GCM, `N` is the nonce that gets incremented after each chunk and `A`  is the compressed associated data. 

For being able to en/decrypt data streams in a compatible way you would have to re-implement *exactly* what `sio-go` does at the moment. Currently, there is no Java or python implementation.

**Comment by Sam-Kramer** [comment]
Thanks for this @aead ! I was able to get a Java implementation working for my use-case (1 chunk only, but will suffice for my needs, as I just need this for encrypting secret-keys for MinIO). Will share on this issue once it has been pushed, so others can easily take/adapt the code to support N-chunks.

**Comment by Sam-Kramer** [comment]
here is the gist of the code, it's pretty ugly: https://gist.github.com/Sam-Kramer/5fc8912a814f9e1a8f9ae412422595f4

will close the issue for now. thanks again!
